INSERT INTO "Medicine" (medicine_name, medicine_information) VALUES
('Paracetamol', 'Usado para aliviar a dor e reduzir febre.'),
('Ibuprofeno', 'Anti-inflamatório não esteróide, alivia a dor e reduz inflamações.'),
('Amoxicilina', 'Antibiótico utilizado para tratar uma variedade de infecções bacterianas.'),
('Cetamol', 'Analgésico e antipirético.'),
('Ibruvix', 'Anti-inflamatório não esteroide.'),
('Amoxilin', 'Antibiótico de amplo espectro.'),
('Rinotad', 'Descongestionante nasal.'),
('Gastrotex', 'Medicamento para úlcera péptica.'),
('Metmorfina', 'Medicamento antidiabético.'),
('Lisoprin', 'Anti-hipertensivo.'),
('Fluoxetina', 'Antidepressivo.'),
('Simvastol', 'Hipolipemiante para colesterol.'),
('Loratamed', 'Antialérgico.'),
('Cetamol', 'Analgésico e antipirético.'),
('Ibruvix', 'Anti-inflamatório não esteroide.'),
('Amoxilin', 'Antibiótico de amplo espectro.'),
('Rinotad', 'Descongestionante nasal.'),
('Gastrotex', 'Medicamento para úlcera péptica.'),
('Metmorfina', 'Medicamento antidiabético.'),
('Lisoprin', 'Anti-hipertensivo.'),
('Fluoxetina', 'Antidepressivo.'),
('Simvastol', 'Hipolipemiante para colesterol.'),
('Loratamed', 'Antialérgico.'),
('Dipirona', 'Analgésico e antitérmico.'),
('Azitromax', 'Antibiótico para infecções bacterianas.'),
('Omeprazol', 'Inibidor da bomba de prótons.'),
('Paroxetil', 'Medicação para transtorno de pânico.'),
('Sertralin', 'Medicamento para depressão e ansiedade.'),
('Atorvastatina', 'Para controle do colesterol.'),
('Losartana', 'Tratamento para pressão alta.'),
('Clonazepam', 'Usado para tratar convulsões e pânico.'),
('Amlovasc', 'Bloqueador de canal de cálcio para hipertensão.'),
('Dorflex', 'Relaxante muscular e analgésico.'),
('Diazepan', 'Sedativo e ansiolítico.'),
('Prednisona', 'Corticosteroide anti-inflamatório.'),
('Ciproheptadina', 'Antialérgico.'),
('Diclofenaco', 'Anti-inflamatório.'),
('Glibenclamida', 'Hipoglicemiante oral.'),
('Hidroclorotiazida', 'Diurético.'),
('Enalapril', 'Anti-hipertensivo.'),
('Cloridrato de Propranolol', 'Beta-bloqueador para hipertensão.'),
('Sinvastacor', 'Redutor de lipídios.'),
('Tadalafila', 'Tratamento para disfunção erétil.'),
('Sulfato de Salbutamol', 'Broncodilatador para asma.'),
('Cetoprofeno', 'Analgésico e anti-inflamatório.'),
('Risperidona', 'Antipsicótico.'),
('Captopril', 'Anti-hipertensivo.'),
('Levotiroxina', 'Hormônio tireoidiano.'),
('Meloxicam', 'Anti-inflamatório.'),
('Citalopran', 'Antidepressivo.'),
('Venlafaxina', 'Antidepressivo.'),
('Naproxeno', 'Anti-inflamatório.'),
('Pantoprazol', 'Inibidor de bomba de prótons.'),
('Espironolactona', 'Diurético poupador de potássio.'),
('Bromoprida', 'Para náusea e vômito.'),
('Baclofeno', 'Relaxante muscular.'),
('Lorazepam', 'Tratamento de ansiedade.'),
('Rosuvastatina', 'Redutor de colesterol.'),
('Cloridrato de Tramadol', 'Analgésico opioide.'),
('Escitalopram', 'Antidepressivo.'),
('Alprazolam', 'Para transtornos de ansiedade.'),
('Donepezila', 'Para demência em pessoas com Alzheimer.'),
('Neurovit', 'Suplemento vitamínico para saúde neural.'),
('Cetirizina', 'Antialérgico.'),
('Cloridrato de Metformina', 'Para diabetes.');


