-- DROP TABLET
DROP TABLE "HistoricMedicalPrescription";
DROP TABLE "MedicalPrescription";
DROP TABLE "Dosage";
DROP TABLE "Medicine";
DROP TABLE "UserRole";
DROP TABLE "Address";
DROP TABLE "Admin";
DROP TABLE "Family";
DROP TABLE "Patient";
DROP TABLE "Medic";
DROP TABLE "HealthCare";
DROP TABLE "UserInfos";
DROP TABLE "User";

-- DROP SEQUENCES
DROP SEQUENCE "user_sequence";
DROP SEQUENCE "address_sequence";
DROP SEQUENCE "admin_sequence";
DROP SEQUENCE "patient_sequence";
DROP SEQUENCE "medic_sequence";
DROP SEQUENCE "healthcare_sequence";
DROP SEQUENCE "family_sequence";
DROP SEQUENCE "dosage_sequence";
DROP SEQUENCE "medicine_sequence";
DROP SEQUENCE "medicalprescription_sequence";
DROP SEQUENCE "historicmedicalprescription_sequence";
